### ISSUE TITLE
프론트 파일 구조 결정

### ISSUE THREAD

**Issue by junmo95** [chirp-community/chirp-community#76]
프론트 기능별 파일 구조 결정

**Comment by iksadNorth** [comment]
# 디렉토리 구조

Root
- src
    - api
        - index.js : 모든 요청에 대해 일괄 처리[로깅, 헤더 관리, 보안 설정, …]가 가능한 파일
    - componentsBoards : 게시판 관련 컴포넌트 디렉토리.
        - index.js : 컴포넌트를 components에 등록하는 파일.
        - Header : 각 컴포넌트를 관리하는 파일.
            - css.css : 해당 컴포넌트에서만 사용 가능한 css 파일.
            - index.js : 작동 내용에 대해 서술한 파일.
     - componentsUsers : 유저 관련 컴포넌트 디렉토리.
        - index.js : 컴포넌트를 components에 등록하는 파일.
        - Header : ...
            - css.css : ...
            - index.js : ...
    - routes
        - index.js : 라우팅과 관련된 설정 파일.
    - utils
        - index.js : 활용성이 높은 메소드 혹은 클래스를 모은 파일.
    - App.js : 최상위 컴포넌트.
    - index.js

**Comment by iksadNorth** [comment]
# 역할 기준으로 디렉토리 분리.
[components] -> [ComponentsUsers, ComponentsBoards]
